package ncBrowse;

import java.util.*;

/**
 * Resource Bundle of menu item tokens and associated
 * locale-specific labels.
 *
 * @author oz
 * @version 1.0
 */

public class NcBrowseResources extends ListResourceBundle {
		public Object[][] getContents() {
			return contents;
 		}

 		static final Object[][] contents = {
 			// American English Menu Strings
 			{"kOK", "OK"},
 			{"kCancel", "Cancel"},
 			{"kFile", "File"},
 			{"kEditMenu", "Edit"},
 			{"kPreferences", "Preferences..."},
 			{"kImportSD2", "Import SD2..."},
 			{"kImportWOCE", "Import WOCE..."},
 			{"kImportSS", "Import Spreadsheet..."},
 			{"kExportSpreadsheet", "Export Spreadsheet..."},
 			{"kFilters", "Filters"},
 			{"kWindows", "Windows"},
 			{"kStationFilter", "Station Filter..."},
 			{"kObservationFilter", "Observation Filter..."},
 			{"kWindows", "Windows"},
 			{"kHelp", "Help..."},
 			{"kHelp2", "Help"},
 			{"kOpen", "Open..."},
 			{"kAddData", "Add Data..."},
 			{"kSave", "Save"},
 			{"kSaveAs", "Save As..."},
 			{"kQuit", "Quit"},
 			{"kExit", "Exit"},
 			{"kPlots", "Plots"},
 			{"kPropertyProperty", "Property-Property..."},
 			{"kProfile", "Profile..."},
 			{"kAbout", "About Java OceanAtlas..."},
 			{"kParameter", "Parameter"},
 			{"kOptions", "Options..."},
 			{"kWindowName", "Window name:"},
 			{"kOffsetBy", "Offset by:"},
 			{"kSequence", "Sequence"},
 			{"kDistance", "Distance"},
 			{"kLatitude", "Latitude"},
 			{"kLongitude", "Longitude"},
 			{"kPlot", "Plot"},
 			{"kMap", "Map..."},
 			{"kPresetRegion", "Preset Region:"},
 			{"kRegion", "Projection/Region"},
 			{"kNorthAtlantic", "North Atlantic"},
 			{"kSouthAtlantic", "South Atlantic"},
 			{"kNorthPacific", "North Pacific"},
 			{"kSouthPacific", "South Pacific"},
 			{"kMediteranean", "Mediteranean"},
 			{"kIndian", "Indian"},
 			{"kArctic", "Arctic"},
 			{"kAntarctic", "Antarctic"},
 			{"kWorld1", "World (Left = 180W)"},
 			{"kWorld2", "World (Left = 20E)"},
 			{"kWorld3", "World (Left = 120E)"},
 			{"kWorld4", "World (Left = 60W)"},
 			{"kWorld", "World"},
 			{"kCustomRegion", "Custom Region"},
 			{"kProjection", "Projection:"},
 			{"kMapCenter", "Map center:"},
 			{"kMercator", "Mercator"},
 			{"kCylindrical", "Miller"},
 			{"kStereographic", "Stereographic"},
 			{"kMollweide", "Mollweide"},
 			{"kOrthographic", "Orthographic"},
 			{"kLambert", "Lambert Azimuthal Equal Area"},
 			{"kBathymetry", "Bathymetry"},
 			{"kStationAndSectionColor", "Station and section color"},
 			{"kBackgroundColor", "Background:"},
 			{"kCoastlineColor", "Coastline:"},
 			{"kGraticuleColor", "Graticule:"},
 			{"kRetainAspect", "Retain cartographic aspect when resizing"},
 			{"kLatSpacing", "Latitude Spacing (deg):"},
 			{"kLonSpacing", "Longitude Spacing (deg):"},
 			{"kMapGraticule", "Map graticule"},
 			{"kSpacing", "Spacing (deg):"},
 			{"kSymbolSize", "Symbol size:"},
 			{"kConnectStations", "Connect stations"},
 			{"kConnectStationsAcross", "Connect stations at section boundaries"},
 			{"kOptions", "Options"},
 			{"kColors", "Colors"},
 			{"kColorBars:", "Color bars:"},
 			{"kXAxisParameter", "X-Axis parameter:"},
 			{"kYAxisParameter", "Y-Axis parameter:"},
 			{"kWindowName", "Window name:"},
 			{"kIncludeColorBar", "Include color bar"},
 			{"kColor", "Color"},
 			{"kCoastline", "Coastline:"},
 			{"kNoCoast", "None"},
 			{"kCoarseRez", "Coarse"},
 			{"kFineRez", "Fine"},
 			{"kColorSchemes", "Styles:"},
 			{"kWhiteBackground", "White background"},
 			{"kBlackBackground", "Black background"},
 			{"kLegend", "Legend"},
 			{"kAxesLabelsColors", "Axes/Text:"},
 			{"kCalculations", "Calculations"},
 			{"kColor", "Color"},
 			{"kParameters", "Parameters..."},
 			{"kColorPaletteEditor", "Color Palette Editor..."},
 			{"kObservationCalculations", "Observation calculations"},
 			{"kTheta", "Theta (Deg. C)"},
 			{"kSigma0", "Sigma 0 (kg/m^2)"},
 			{"kSigma1", "Sigma 1 (kg/m^2)"},
 			{"kSigma2", "Sigma 2 (kg/m^2)"},
 			{"kSigma3", "Sigma 3 (kg/m^2)"},
 			{"kSigma4", "Sigma 4 (kg/m^2)"},
 			/*{"kTheta", "Theta (" + '\u00b2' + "C)"},
 			{"kSigma0", "Sigma 0 (kg/m" + '\u00b3' + ")"},
 			{"kSigma1", "Sigma 1 (kg/m" + '\u00b3' + ")"},
 			{"kSigma2", "Sigma 2 (kg/m" + '\u00b3' + ")"},
 			{"kSigma3", "Sigma 3 (kg/m" + '\u00b3' + ")"},
 			{"kSigma4", "Sigma 4 (kg/m" + '\u00b3' + ")"},*/
 			{"kSigmaRef", "Sigma, ref.="},
 			{"kSpecificVolumeAnomaly", "Specific volume anomaly (m^2/kg)"},
 			{"kSpiciness", "Spiciness"},
 			{"kSoundVelocity", "Sound velocity (m/s)"},
 			{"kO2Sat", "O2 % saturation"},
 			{"kAOU", "AOU"},
 			{"kNO", "NO"},
 			{"kPO", "PO"},
 			{"kVolumeToMass", "Volume->Mass Units (AOU/NO/PO)"},
 			{"kAOU/NO/PO", "(AOU/NO/PO)"},
 			{"kHeatStorage", "Heat Storage"},
 			{"kAlphaBeta", "Alpha/Beta"},
 			{"kAlpha", "Alpha (thermal expansion)"},
 			{"kAlphaDeriv", "Alpha * dT/dz"},
 			{"kBeta", "Beta (saline contraction)"},
 			{"kBetaDeriv", "Beta * dS/dz"},
 			{"kBuoyancyFrequency", "Buoyancy frequency (Hz)"},
 			{"kEFolding", "e-folding length: "},
 			{"kMeters", "(m)"},
 			{"kN", "N"},
 			{"kNSq", "N^2"},
 			{"kFNSqG", "fN^2/g"},
 			{"kIntegralCalculations", "Integral calculations (reference = 0)"},
 			{"kAcousticTravelTime", "Acoustic travel time (sec)"},
 			{"kNetHeatContent", "Net heat content (10^9 J/m^2)"},
 			{"kPotentialEnergyAnomaly", "Potential energy anomaly (10^6 J/m^2)"},
 			{"kGeopotentialAnomaly", "Geopotential anomaly (J/m)"},
 			{"kColorPalettes", "Color palettes:"},
 			{"kPick", "Pick..."},
 			{"kBlend", "Blend"},
 			{"kSave", "Save..."},
 			{"kNew", "New..."},
 			{"kContourManager", "Contour Manager..."},
 			{"kColorbars", "Color bars:"},
 			{"kApply", "Apply"},
 			{"kEdit", "Edit..."},
 			{"kDescription", "Description"},
 			{"kParameter2", "Parameter:"},
 			{"kTitle", "Title:"},
 			{"kStartValue", "Start value:"},
 			{"kEndValue", "End value:"},
 			{"kNumContours", "Number of contours:"},
 			{"kAssignFromTable", "Assign colors from color table"},
 			{"kBlendColors", "Blend colors"},
 			{"kAssignFromRainbow", "Rainbow"},
 			{"kAssignFromInvRainbow", "Inverse Rainbow"},
 			{"kStartColor", "Start color:"},
 			{"kAssignColors", "Assign colors:"},
 			{"kAcrossTable", "Across table"},
 			{"kDownTable", "Down table"},
 			{"kMiddleColor", "Middle color:"},
 			{"kEndColor", "End color:"},
 			{"kInitialShape", "Initial shape:"},
 			{"kColorAssignment", "Color assignment"},
 			{"kCreate", "Create"},
 			{"kCreateCalculation", "Create Calculation"},
 			{"kPendingCalculations", "Pending calculations:"},
 			{"kColorPalettes", "Color Palettes:"},
 			{"kValue", "Value:"},
 			{"kValueEditor", "Value Editor"},
 			{"kCreateWithShape", "Create with shape:"},
 			{"kColorBarPreview", "Color Bar Preview"},
 			{"kDescription2", "Description:"},
 			{"kContours", "Contours"},
 			{"kValueEditorPreview", "Value editor/preview"},
 			{"kDelete", "Delete"},
 			{"kDone", "Cancel"},
 			{"kMakeDefault", "Make Default"},
 			{"kMakeDefault...", "Make Default..."},
 			{"kLevels", "Levels"},
 			{"kNumLevels", "Number of levels"},
 			{"kFirstLevel", "First level:"},
 			{"kLastLevel", "Last level:"},
 			{"kLevelEditor", "Level editor"},
 			{"kInterpolationSurfaces", "Interpolation surfaces"},
 			{"kSurfaceManager", "Surface Manager..."},
 			{"kResources", "Resources"},
 			{"kInterpolationSurfaces", "Interpolation surfaces"},
 			{"kExistingInterpolations", "Existing interpolations"},
 			{"kInterpolationName", "Interpolation name:"},
 			{"kInterpolate", "Interpolate"},
 			{"kVerticalInterpolations", "Vertical Interpolations..."},
 			{"kInterpolationDirection", "Interpolation direction"},
 			{"kInterpolationDirectioncolon", "Interpolation direction:"},
 			{"kIntegrationDirectioncolon", "Integration direction:"},
 			{"kReferenceLevel", "Reference level"},
 			{"kTopDown", "Top down"},
 			{"kBottomUp", "Bottom up"},
 			{"kValueOf", "Value of"},
 			{"kStyle", "Contour Style"},
 			{"kContourLines", "Lines only"},
 			{"kFiledl", "Filled"},
 			{"kColorFillWContours", "Filled w/lines"},
 			{"kOffset", "Offset"},
 			{"kMarkers", "Markers"},
 			{"kNone", "None"},
 			{"kSurfaceLevels", "Surface levels"},
 			{"kObservations", "Observations"},
 			{"kColorLegend", "Color legend"},
 			{"kEnableBrowsing", "EnableBrowsing"},
 			{"kShowCrossSections", "Cross sections"},
 			{"kYAxisRange", "Y axis range:"},
 			{"kMinimum", "Minimum:"},
 			{"kMaximum", "Maximum:"},
 			{"kMinimum2", "Minimum"},
 			{"kMaximum2", "Maximum"},
 			{"kMin", "Min"},
 			{"kMax", "Max"},
 			{"kAutoscale", "Autoscale"},
 			{"kContour", "Contour..."},
 			{"kOther", "Other"},
 			{"kBasedOn", "Based on:"},
 			{"kCreateAutoscaleColorbar", "Create autoscale color bar"},
 			{"kShape", "Shape:"},
 			{"kUsing", "Using:"},
 			{"kBottles", "(bottles)"},
 			{"kPlotAxes", "Plot axes"},
 			{"kHorizontalInterpolation", "Horizontal interpolation"},
 			{"kVerticalInterpolation", "Vertical interpolation"},
 			{"kCasts", "(casts)"},
 			{"kDistanceColon", "Distance:"},
 			{"kMaxDistanceColon", "Maximum distance:"},
 			{"kKM", "(km)"},
 			{"kConnectObservations", "Connect observations"},
 			{"kCustomParameter", "Custom Parameter..."},
 			{"kParameterTransformations", "Parameter Transformations..."},
 			{"kTransformations", "Transformations"},
 			{"kConstant", "Constant:"},
 			{"kNewParameterName", "New parameter name:"},
 			{"kReverseWhenY", "Reverse when plotted as Y axis parameter?"},
 			{"kParameter1", "Parameter 1:"},
 			{"kParameter2Colon", "Parameter 2:"},
 			{"kAdvancedOptions", "Advanced Options"},
 			{"kPlotAxes", "Plot axes"},
 			{"kYGrid", "Y Grid"},
 			{"kXGrid", "X Grid"},
 			{"kXAxis", "X-Axis"},
 			{"kYAxis", "Y-Axis"},
 			{"kIncrement", "Increment:"},
 			{"kNoMinorTicks", "# of minor ticks:"},
 			{"kUseDataMaxMin", "Use Data Max/Mins"},
 			{"kDataMaxMin", "Data Max/Min"},
 			{"kPlotSymbol", "Plot symbol:"},
 			{"kSymbol", "Symbol:"},
 			{"kSize", "Size:"},
 			{"kAxes", "Axes"},
 			{"kBlackBG", "Black background"},
 			{"kReverseStations", "Reverse stations"},
 			{"kMergeCasts", "Merge multiple casts at same station "},
 			{"kMergeSections", "Merge all stations into one section (creates new section)"},
 			{"kSortAllStns", "Re-order/Sort/Delete stations (creates new section)"},
 			{"kAmplitude", "Amplitude:"},
 			{"kTraceOffset", "Trace offset"},
 			{"kPixels", "(pixels)"},
 			{"kNMPerPixel", "(nm/pixel)"},
 			{"kLineWidthColon", "Line width:"},
 			{"kAxes", "Axes"},
 			{"kXAxisRange", "X Axis Range"},
 			{"kYAxisRange", "Y Axis Range"},
 			{"kAxes", "Axes"},
 			{"kCurrentObservation", "Current Observation"},
 			{"kEmpty", ""},
 			{"kCurrentStation", "Current Station"},
 			{"kIsopycnals", "Isopycnals"},
 			{"kReferencePressure", "Reference pressure:"},
 			{"kPressure", "Pressure:"},
 			{"kAnd", "And"},
 			{"kOr", "Or"},
 			{"kCondition1", "Condition 1"},
 			{"kCondition2", "Condition 2"},
 			{"kDisplayOptions", "Display options"},
 			{"kShowMatching", "Show only matching observations"},
 			{"kHighlight", "Highlight matching observation"},
 			{"kEnlargeSymbol", "Enlarge current symbol"},
 			{"kUseNewSymbols", "Contrasting symbol:"},
 			{"kLocationFilter", "Location Filter"},
 			{"kStationSelectionFilter", "Station/Section Filter"},
 			{"kIncludeStations", "Include stations"},
 			{"kExcludeStations", "Exclude stations"},
 			{"kMissingParameterFilter", "Missing Parameter Filter"},
 			{"kStationColors", "Station Colors"},
 			{"kIsoSurface", "Iso-surface/station value"},
 			{"kAssignedStnColors", "JOA assigned colors"},
 			{"kParameter:", "Parameter:"},
 			{"kColorMapping", "Color mapping:"},
 			{"kSurface", "Surface:"},
 			{"kMapColors", "Map Colors"},
 			{"kColors:", "Colors:"},
 			{"kBottomUpSearch", "Bottom up search"},
 			{"kOverlayContours", "Overlay contours:"},
 			{"kPlotEvery", "Plot every:"},
 			{"kLabelEvery", "Label every:"},
 			{"kContours", "(nd, rd, th) contour"},
 			{"kColorLines", "Color contour lines"},
 			{"kContourOptions", "Options..."},
 			{"kDefault", "Default"},
 			{"kGridColor", "Grid color"},
 			{"kInterpOptions", "Interpolation Options..."},
 			{"kPrint", "Print..."},
 			{"kConnectLineWidth", "Connect observations line width: "},
 			{"kLineWidth", "Line width"},
 			{"kMissingValColor", "Missing value color"},
 			{"kPlotBGColor", "Plot background color"},
 			{"kPlotInteriorColor", "Plot interior color"},
 			{"kSectionWidth", "Section width:"},
 			{"kSelectedStations", "Selected Stations"},
 			{"kStoN", "S->N"},
 			{"kStoNSpecial", "S->N (required for latitude offset)"},
 			{"kNtoS", "N->S"},
 			{"kEtoW", "E->W"},
 			{"kWtoE", "W->E"},
 			{"kWtoESpecial", "W->E (required for longitude offset)"},
 			{"kStnDsc", "Stn. number (dsc)"},
 			{"kStnAsc", "Stn. number (asc)"},
 			{"kDateDsc", "Date (dsc)"},
 			{"kDateAsc", "Date (asc)"},
 			{"kSorting", "Sorting"},
 			{"kNewSectionName", "New section name:"},
 			{"kSort", "Sort"},
 			{"kLineSpacing", "Line spacing:"},
 			{"kNorthPole", "North Pole"},
 			{"kSouthPole", "South Pole"},
 			{"kCentralAtlantic", "Central Atlantic"},
 			{"kCentralPacific", "Central Pacific"},
 			{"kDistanceLegend", "Distance (km)"},
 			{"kLatitudeLegend", "Latitude"},
 			{"kLongitudeLegend", "Longitude"},
 			{"kSequenceLegend", "Station Ordinal"},
 			{"kSectionManager", "Section Manager..."},
 			{"kActions", "Actions"},
 			{"kReverseStations", "Reverse stations"},
 			{"kProperties", "Properties..."},
 			{"kNews", "JOA News..."},
 			{"kExportPOABinary", "Export POA Binary..."},
 			{"kStationSelection", "Station Selection"},
 			{"kSection", "Section:"},
 			{"kStationNumber", "Station number:"},
 			{"kCastNumber", "Cast number:"},
 			{"kLatitudeColon", "Latitude:"},
 			{"kShipCode", "Ship:"},
 			{"kDate", "Date:"},
 			{"kLongitudeColon", "Longitude:"},
 			{"kBottom", "Bottom:"},
 			{"kMM", "MM:"},
 			{"kDD", "DD:"},
 			{"kYYYY", "YYYY:"},
 			{"kHH", "HH"},
 			{"kMM.M", "MM.M:"},
 			{"kXAxisScale", "X Axis Scale"},
 			{"kCustom", "Custom:"},
 			{"kkm/cm", "(km/pix)"},
 			{"kdeg/cm", "(deg/pix)"},
 			{"kstn/cm", "(stns/pix)"},
 			{"kInterpolationLevel", "Interpolation Level"},
 			{"kMissingValueOptions", "Missing Value Options"},
 			{"kReferencedTo", "Referenced To"},
 			{"kMeanCast", "Mean Cast (select stations to average)"},
 			{"kLon", "Lon:"},
 			{"kLat", "Lat:"},
 			{"kUnits", "Units:"},
 			{"kDisplayUnits", "Display units in data window"},
 			{"kName", "Name:"},
 			{"kPolar", "Polar"},
 			{"kReverseY", "Reverse Y"},
 			{"kReverseYAxis", "Reverse Y axis"},
 			{"kFileComments", "File Comments"},
 			{"kNews", "JOA News"},
 			{"kImport", "Import"},
 			{"kPOA", "Power OceanAtlas..."},
 			{"kSS", "Spreadsheet (TSV)..."},
 			{"kSD2", "SD2..."},
 			{"kSD3", "SD3..."},
 			{"kWOCE", "WOCE Hydrographic..."},
 			{"kPixPerKM", "(pixel/km)"},
 			{"kNoDecimation", "No decimation"},
 			{"kConstant", "Constant"},
 			{"kEvery", "every"},
 			{"kDB", "(db)"},
 			{"kDate", "Date:"},
 			{"kStandardLevels", "Standard levels:"},
 			{"kGeneral", "General"},
 			{"kCTDDecimation", "CTD Decimation"},
 			{"kWoceImport", "WOCE Import"},
 			{"kCustomDotDotDot", "Custom..."},
 			{"kExportNetCDF", "Export netCDF Section..."},
 			{"kConvertTemp", "Convert temperatures from ITS90 to IPTS68 (required for density calculations)"},
 			{"kConvertMassToVol", "Convert from mass to volume units"},
 			{"kReplaceMsg1", "Replace with missing value when parameter quality code is:"},
 			{"kReplQB3", "3 (Questionable value)"},
 			{"kReplQB7", "7 (Manual CFC)"},
 			{"kReplQB4", "4 (Bad measurement)"},
 			{"kReplQB8", "8 (Irregular CFC)"},
 			{"kMergeCasts", "Merge multiple casts at same station (creates new section)"},
 			{"kReplaceAllBottleParams", "Set ALL bottle parameters missing when bottle quality code=4"},
 			{"kReplaceAllGasParams", "Set gas parameters missing where bottle quality code=2 and bottle oxygen quality code=4"},
 			{"kDisplayQC", "Display quality codes in data window"},
 			{"kColorByQC", "Color symbols by bottle quality code"},
 			{"kIsobaths", "Isobaths"},
 			{"kLockRgn", "Lock region"},
 			{"kColorFill", "Color fill"},
 			{"kColorFillBathy", "Color Fill Bathymetry"},
 			{"kResolution", "Resolution:"},
 			{"kContrastColor", "Contrasting color:"},
 			{"kSaveGraphic", "Save plot as GIF..."},
 			{"kSaveData", "Save data..."},
 			{"kAssignColorsOnly", "Assign colors only"},
 			{"kPlotOlnyCurrStn", "Plot current station only     "},
 			{"kPlotUsingCB", "Color plot by current colorbar"},
 			{"kBrowse", "Bowse collections..."},
 			{"kView", "View"},
 			{"kZoom", "Zoom"},
 			{"kExportEPICPtr", "Export EPIC Pointer File..."},
 			{"kExportStnCalcs", "Export Station Calculations..."},
 			{"kSaveSettings", "Save settings..."},
 			{"kReadSettings", "Read settings..."},
 			{"kLoad", "Load..."},
 			{"kSaveInterpolation", "Save Values..."},
 			{"kDelimiter", "Delimiter"},
 			{"kTab", "Tab"},
 			{"kComma", "Comma"},
 			{"kUDDelimiter", "User Defined:"},
 			{"kMissingValue", "Missing Value"},
 			{"kDefaultMissing", "JOA Default Missing Value (-99)"},
 			{"kCustomMissingValue", "User Defined Missing Value:"},
 			{"kStationCalculation", "Station Calculations..."},
 			{"kWRT", "With respect to:"},
 			{"kSurfaceAsMin", "Use shallowest observation if needed"},
 			{"kBottomAsMax", "Use deepest observation if needed"},
 			{"kComputeWeightedMean", "Compute weighted mean"},
 			{"kSurfaceMethod", "Surface method"},
 			{"kStartDepthOfSurface", "Minimum depth:"},
 			{"kMaxDepthOfSurface", "Maximum depth:"},
 			{"kDepthOfDifference", "Starting depth of difference calculation:"},
 			{"kDepthOfSlope", "Starting depth of slope calculation:"},
 			{"kSlopeMethod", "Slope method"},
 			{"kTolerance", "Tolerance:"},
 			{"kIntegrand", "Integrand:"},
 			{"kIntegration", "Integration"},
 			{"kMixedLayer", "Depth of Mixed Layer"},
 			{"kTestParameter", "Test Parameter"},
 			{"kDifferenceMethod", "Difference method"},
 			{"kStnPlot", "Station Value Plot..."},
 			{"kTranslateQC", "Translate WOCE quality codes to IGOSS"},
 			{"kMapTab1", "General Settings"},
 			{"kMapTab2", "Bathymetry"},
 			{"kMapTab3", "Station Colors"},
 			{"kContourTab1", "Basic"},
 			{"kContourTab2", "Advanced"},
 			{"kMixedSearch", "Search down for min and up for max"},
 			{"kInterpMissing", "Interpolate missing values"},
 			{"kShowNdedit", "Show NdEdit"},
 			{"kWindows", "Windows"},
 			{"kConnectLineColor", "Connect line color"},
 			{"kTestParameter", "Test Parameter"},
 			{"kParameterOrder", "Parameter order"},
 			{"kXAxes", "X Axes:"},
 			{"kSelectFilter", "Select saved filter:"},
 			{"kMapColor", "Map color:"},
 			{"kShowSectionEditor", "Section Editor..."},
 			{"kPlotSectionLabels", "Plot section labels"},
 			{"kRemove", "Remove"},
 			{"kClearAll", "Clear All"},
 			{"kClose", "Close"},
 			{"kPlotLabels", "Plot graticule labels"},
 			{"kLabels", "Labels:"},
 			{"kAutomatic", "Automatic"},
 			{"kBathymetryFiles", "Bathymetry files:"},
 			{"kFileProperties", "File Properties..."},
 			{"kParamProperties", "Parameter Properties..."},
 			{"kTranslateParamNames", "Translate parameter names on read and import"},
 			{"kJOAPreferences", "JOA Preferences..."},
 			{"kIncludeBrowser", "Observation browser"},
 			{"kDefaultAutoscaleColorScheme", "Default autoscale color scheme:"},
 			{"kMergeObservations", "Average observed values at same pressure"},
 			{"kGratLabels", "Graticule Labels"},
 			{"kTranslateOrigin", "Translate origin:"},
 			{"kOpenDODS", "Open DODS..."},
 			{"kBlueLegend", "Out-Of-Range Max"},
 			{"kYellowLegend", "Out-Of-Range Min"},
 			{"kRedLegend", "Out-Of-Range Max and Min"},
 			{"kBrowserSymbol", "Browsing cursor symbol:"},
 			{"kStationSymbol", "Station symbol:"},
 			{"kOrientation", "Orientation"},
 			{"kXFacePos", "X Face (+)"},
 			{"kXFaceNeg", "X Face (-)"},
 			{"kYFacePos", "Y Face (+)"},
 			{"kYFaceNeg", "Y Face (-)"},
 			{"kZFacePos", "Z Face (+)"},
 			{"kZFaceNeg", "Z Face (-)"},
 			{"kRotateX", "Rotate X Axis"},
 			{"kWobbleX", "Wobble X Axis"},
 			{"kRotateY", "Rotate Y Axis"},
 			{"kWobbleY", "Wobble Y Axis"},
 			{"kRotateZ", "Rotate Z Axis"},
 			{"kWobbleZ", "Wobble Z Axis"},
 			{"kClear", "Clear"},
 			{"kDDone", "Done"},
 			{"kCustomOrient", "Custom Orientation..."},
 			{"kAzimuth", "Azimuth:"},
 			{"kDeclination", "Declination:"},
 			{"kParameterEditor", "Parameter Editor"},
 			{"kParameters2", "Parameters"},
 			{"kPlotOptions", "Plot Options"},
 			{"kReverseZ", "Reverse Z"},
 			{"kReverseX", "Reverse X"},
 			{"kReverseY", "Reverse Y"},
 			{"kNo3DLegend", "No legend"},
 			{"kColorBarLegend", "Color bar legend"},
 			{"kRemapperLegend", "Remapping legend"},
 			{"kResample", "Resample data if axes are different lengths"},
 			{"kVectorScale", "Vector scale factor:"},
 			{"kIncludeComponents", "Include components: "},
 			{"kU", "U"},
 			{"kV", "V"},
 			{"kW", "W"},
 			{"kWeightedAverage", "Weighted average"},
 			{"kNearestNeighbor", " Nearest neighbor"},
 			{"kSamplingMode", "Sampling mode:"},
 			{"kRespectAspectRatio", "Use aspect ratio of data"},
 			{"kXScaling", "X:"},
 			{"kYScaling", "Y:"},
 			{"kZScaling", "Z:"},
 			{"kSaveAsPNG", "Save plot as PNG file..."},
 			{"kAxesColor", "Axes color:"},
 			{"kBackgroundColor2", "Background color:"},
 			{"kVariableMapName", "Variable Map Name:"},
 			{"kSource", "Source:"},
 			{"kTarget", "Target:"},
 			{"kShowAllDimensions", "Show All Dimensions"},
 			{"kVariableMapmustbenamed", "Variable Map must be named."},
 			{"kVComponent", "V Component:"},
 			{"kContour2", "Contour:"},
 			{"kUComponent", "U Component"},
 			{"kWComponent", "W Component"},
 			{"kYAxisVariable", "Y Axis:"},
 			{"kXAxisVariable", "X Axis:"},
 			{"kZAxisVariable", "Z Axis:"},
 			{"kColorVariable", "Line color:"},
 			{"kSurfaceColor", "Surface color:"},
 			{"kVariableMap", "Variable Map..."},
 			{"kVolume", "Volume:"},
 			{"kScaleFactor", "Scale Factor:"},
 			{"kAdvancedOptions2", "Advanced Options..."},
 			{"kCustomOrientation", "3D Custom Plot Orientation"},
 			{"k3DAdvancedOptions", "3D Advanced Plot Options"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			{"kFuture", "Future"},
 			
 			{"kParamFilterHelp", "Exclude stations " +
					 	  "\n" +
 						  "missing observations " +
					 	  "\n" +
					 	  "of selected parameters " +
					 	  "\n" +
					 	  "(select one or more.)"},
 			
			{"kDifferenceHelp",
						   "Difference Method:  The mixed layer is defined as the depth where the " + "\n" +
						   "difference between the value of the parameter and the value of parameter " + "\n" +
						   "at the specified depth is greater than the specified tolerance." + "\n"},
 			
			{"kSurfaceHelp",
						   "JOA first computes a surface layer by computing the mean " + "\n" +
						   "of the selected parameter from the surface (or shallowest bottle) " + "\n" +
						   "to the maximum depth specified. The mixed layer is defined as the " + "\n" +
						   " depth where the difference between the value of the parameter " + "\n" +
						   "and the value of the surface layer is greater than the specified tolerance." + "\n"},
 			
			{"kSlopeHelp",
						   "Slope Method: The mixed layer is defined as the depth where the " + "\n" +
						   "difference in the gradient (slope) of the selected parameter is " + "\n" +
						   "greater than the specified tolerance." + "\n"},
 			
			{"kQBEditorHelp",
						   "The Quality Byte Editor Feature is used to assign or change the value " +
						   "of individual values of Quality Byte 1 (assigned by the data originator) " +
						   "or Quality Byte 2 (assigned by WOCE data quality expert.)" +
					 	  "\n" +
					 	  "\n" +
						 "Click the Setup button to establish which parameters, and how many lines of "+
						 "the data will be displayed on the screen. Click the Find button to move around "+
						 "in the data set. "+
					 	  "\n"}
		};
}