/* Generated by Together */

package ncBrowse.sgt.contour;
/**
 * Not implemented.
 */
public class TreeEnumerator implements java.util.Enumeration {
    public boolean hasMoreElements() {
        return false;
    }
    public Object nextElement() {
        return null;
    }
}
